# Generated by Django 4.0.3 on 2022-05-24 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_coupon_is_use_coupon_used_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='created_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
