# Generated by Django 4.0.3 on 2022-05-24 23:54

import coupon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_coupon_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=coupon.models.path_and_rename),
        ),
    ]
