# Generated by Django 4.0.3 on 2022-05-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_coupon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='created_date',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
