# Generated by Django 4.0.3 on 2022-06-06 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_certificatecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatecode',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
