# Generated by Django 4.0.3 on 2022-06-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_certificatecode_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatecode',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
